# Generated by Django 4.2 on 2023-05-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeid', models.IntegerField()),
                ('recipename', models.CharField(max_length=200)),
            ],
        ),
    ]
